USE [master]
GO

/****** Object:  Database [Recipes]    Script Date: 7/22/2014 8:47:09 PM ******/
DROP DATABASE [Recipes]
GO

/****** Object:  Database [Recipes]    Script Date: 7/22/2014 8:47:09 PM ******/
CREATE DATABASE [Recipes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Recipes', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Recipes.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Recipes_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Recipes_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Recipes] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Recipes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Recipes] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Recipes] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Recipes] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Recipes] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Recipes] SET ARITHABORT OFF 
GO

ALTER DATABASE [Recipes] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Recipes] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Recipes] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Recipes] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Recipes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Recipes] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Recipes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Recipes] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Recipes] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Recipes] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Recipes] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Recipes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Recipes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Recipes] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Recipes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Recipes] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Recipes] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Recipes] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Recipes] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Recipes] SET  MULTI_USER 
GO

ALTER DATABASE [Recipes] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Recipes] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Recipes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Recipes] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Recipes] SET  READ_WRITE 
GO

